vim.o.number = true           -- Mostrar números de línea
vim.o.relativenumber = true   -- Números relativos
vim.o.expandtab = true        -- Convertir tabs en espacios
vim.o.shiftwidth = 4          -- Tamaño de indentación
vim.o.tabstop = 4             -- Número de espacios para tabulación
vim.o.softtabstop = 4
vim.b.is_codeium_suggestion = true;
vim.opt.hidden = true            -- Permitir buffers ocultos
vim.opt.splitbelow = true        -- Las nuevas ventanas se abrirán debajo
vim.opt.splitright = true        -- Las nuevas ventanas se abrirán a la derecha
vim.opt.cursorline = true
